'use strict';
const data=window.PITCH_DATA;
const pages=[...document.querySelectorAll('.page')];
const navigation=[...document.querySelectorAll('[data-page]')];
function showPage(){const id=location.hash.slice(1)||'overview';const page=pages.find(p=>p.id===id)||pages[0];pages.forEach(p=>{p.hidden=p!==page;p.classList.toggle('active',p===page)});navigation.forEach(a=>{if(a.dataset.page===page.id)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});document.getElementById('breadcrumb').textContent=navigation.find(a=>a.dataset.page===page.id).textContent.trim().replace(/^\d+\s*/, '');document.title=`InSilicon — ${document.getElementById('breadcrumb').textContent}`;window.scrollTo(0,0);}
window.addEventListener('hashchange',()=>{showPage();document.getElementById('main').focus({preventScroll:true})});showPage();
const phaseTabs=document.querySelector('.phase-tabs');
data.phases.forEach((phase,i)=>{const b=document.createElement('button');b.id='phase-tab-'+phase.id;b.setAttribute('role','tab');b.setAttribute('aria-controls','phase-detail');b.innerHTML=`<strong>PHASE 0${phase.id}</strong>${phase.name}`;b.addEventListener('click',()=>selectPhase(i));b.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(i+1)%3;if(e.key==='ArrowLeft')next=(i+2)%3;if(e.key==='Home')next=0;if(e.key==='End')next=2;if(next!==undefined){e.preventDefault();selectPhase(next);phaseTabs.children[next].focus()}});phaseTabs.append(b)});
function selectPhase(index){const p=data.phases[index];[...phaseTabs.children].forEach((b,i)=>{b.setAttribute('aria-selected',String(i===index));b.tabIndex=i===index?0:-1});const detail=document.getElementById('phase-detail');detail.setAttribute('aria-labelledby','phase-tab-'+p.id);detail.innerHTML=`<div class="phase-layout"><div><div class="phase-number">0${p.id}</div><p class="eyebrow">${p.period}</p><h2>${p.headline}</h2><p>${p.description}</p><div class="gate"><span>CAPITAL BOUNDARY</span><p>${p.capital}</p></div></div><div class="phase-detail-list"><h3>Proposed deliverables</h3><ul class="clean-list">${p.deliverables.map(x=>`<li>${x}</li>`).join('')}</ul><div class="gate"><span>INVESTMENT GATE</span><p>${p.gate}</p></div></div></div>`;}
selectPhase(0);
const defaults={clients:8,fee:2.5,margin:70,opex:22,months:18,setup:25,buffer:20};
const money=v=>`${v<0?'−':''}₹${Math.abs(v)>=100?(Math.abs(v)/100).toFixed(2)+' cr':Math.abs(v).toFixed(1)+' L'}`;
function calculate(v){const revenue=v.clients*v.fee*12,grossProfit=revenue*v.margin/100,annualOpex=v.opex*12,profit=grossProfit-annualOpex;return {annualRevenue:revenue,annualGrossProfit:grossProfit,annualFixedOpex:annualOpex,annualOperatingResult:profit,breakEvenCustomers:Math.ceil(v.opex/(v.fee*v.margin/100)),grossFunding:(v.opex*v.months+v.setup)*(1+v.buffer/100),steadyStateFunding:(Math.max(0,v.opex-grossProfit/12)*v.months+v.setup)*(1+v.buffer/100)};}
let modelState;
function updateModel(){const form=document.getElementById('model-form');if(!form.checkValidity())return;const v=Object.fromEntries(Object.keys(defaults).map(k=>[k,Number(document.getElementById(k).value)]));const r=calculate(v);modelState={inputs:v,outputs:r};document.getElementById('clients-value').textContent=v.clients;document.getElementById('fee-value').textContent='₹'+v.fee.toFixed(2)+' lakh';document.getElementById('margin-value').textContent=v.margin+'%';document.getElementById('opex-value').textContent='₹'+v.opex+' lakh';document.getElementById('arr-result').textContent=money(r.annualRevenue);document.getElementById('arr-detail').textContent=`${v.clients} customers × ₹${v.fee.toFixed(2)} lakh × 12 months`;document.getElementById('profit-result').textContent=money(r.annualOperatingResult);document.getElementById('profit-result').className=r.annualOperatingResult<0?'negative':'positive';document.getElementById('breakeven-result').textContent=r.breakEvenCustomers;document.getElementById('gross-result').textContent=money(r.grossFunding);document.getElementById('net-result').textContent=money(r.steadyStateFunding);const bars=[['Revenue',r.annualRevenue],['Gross profit',r.annualGrossProfit],['Fixed opex',r.annualFixedOpex]];const max=Math.max(...bars.map(a=>a[1]),1);document.getElementById('result-bars').innerHTML=bars.map(([label,val])=>`<div class="bar-row"><span>${label}</span><div class="bar-track" aria-hidden="true"><div class="bar-fill" style="width:${val/max*100}%"></div></div><b>${money(val)}</b></div>`).join('');document.querySelectorAll('[data-scenario]').forEach(b=>{const active=Number(b.dataset.scenario)===v.clients;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',String(active))})}
Object.keys(defaults).forEach(k=>document.getElementById(k).addEventListener('input',updateModel));document.getElementById('model-form').addEventListener('submit',e=>e.preventDefault());document.querySelectorAll('[data-scenario]').forEach(b=>b.addEventListener('click',()=>{document.getElementById('clients').value=b.dataset.scenario;updateModel()}));document.getElementById('reset-model').addEventListener('click',()=>{Object.entries(defaults).forEach(([k,v])=>document.getElementById(k).value=v);updateModel()});
document.getElementById('export-model').addEventListener('click',()=>{const payload={company:'InSilicon',status:'Illustrative planning assumptions, not forecasts or actual results',currency:'INR',units:'lakh',exportedAt:new Date().toISOString(),...modelState,exclusions:['Onboarding','Cloud and EDA pass-through','Customer ramp and churn','Tax and financing','Working capital and cash on hand','Phase 2 and Phase 3'],method:'Revenue = clients × monthly fee × 12. Gross profit = revenue × gross margin. Operating result = gross profit − monthly opex × 12. Funding formulas are disclosed in dashboard.'};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download='InSilicon_Scenario_Assumptions.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});updateModel();
const risks=[['EDA and PDK rights','Founder + EDA lead','Confirm permitted hosting, cloud regions and service-provider scope before customer onboarding. Do not assume an ordinary end-user license permits reselling tool access.'],['Customer IP and AI data use','SRE / security lead','Implement project isolation, encryption, access reviews, audit logs and tested recovery. Keep customer design data out of external AI training unless explicitly permitted.'],['Weak service economics','Founder + finance','Track support hours, margin, collections and concentration. Validate willingness to pay and separate fixed staff costs from variable delivery costs without double counting.'],['Tool and cloud variability','Platform + EDA leads','Maintain a versioned tool/OS/PDK compatibility matrix and benchmark reference workloads. Choose one cloud first and qualify any second cloud independently.'],['Premature silicon or facility investment','Board / investors','Require a customer-backed specification and separately financed tapeout program. Approve campus and fabrication commitments only after feasibility, demand and partner evidence.']];document.getElementById('risk-list').innerHTML=risks.map(([name,owner,body])=>`<details class="risk"><summary>${name}<span>${owner} +</span></summary><p>${body}</p></details>`).join('');document.getElementById('sources-list').innerHTML=data.sources.map(s=>`<a href="${s.url}" target="_blank" rel="noopener noreferrer"><span>${s.id}</span><div>${s.title}<small>${s.use}</small></div><span>↗</span></a>`).join('');

// Funding scenario toggle
const fundingScenarios={3:{label:'BASE RAISE',amount:'$3.0<span>M</span>',detail:'18-month execution capital',financingLabel:'BASE FINANCING CASE',financingAmount:'$3.00M'},5:{label:'ACCELERATED RAISE',amount:'$5.0<span>M</span>',detail:'Scale after commercial evidence',financingLabel:'ACCELERATED FINANCING CASE',financingAmount:'$5.00M'}};
function selectFundingScenario(value){const key=Number(value);const x=fundingScenarios[key];if(!x)return;document.querySelectorAll('[data-funding]').forEach(b=>{const active=Number(b.dataset.funding)===key;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',String(active));});const label=document.getElementById('funding-label'),amount=document.getElementById('funding-amount'),detail=document.getElementById('funding-detail'),fl=document.getElementById('financing-label'),fa=document.getElementById('financing-amount');if(label)label.textContent=x.label;if(amount)amount.innerHTML=x.amount;if(detail)detail.textContent=x.detail;if(fl)fl.textContent=x.financingLabel;if(fa)fa.textContent=x.financingAmount;}
document.querySelectorAll('[data-funding]').forEach(b=>b.addEventListener('click',()=>selectFundingScenario(b.dataset.funding)));
selectFundingScenario(3);
